// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCyNuW2rJBKL6pZWiBPsaxCVkDLssBtM',
    appId: '1:792709871499:web:e312606ef9fae41776618e',
    messagingSenderId: '792709871499',
    projectId: 'foodapp-27652',
    authDomain: 'foodapp-27652.firebaseapp.com',
    storageBucket: 'foodapp-27652.firebasestorage.app',
    measurementId: 'G-L8XMV57TEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzS8FLzZmhR8KwnCRdKjRHEnKDk41gqo',
    appId: '1:792709871499:android:abeacad3e3a094e576618e',
    messagingSenderId: '792709871499',
    projectId: 'foodapp-27652',
    storageBucket: 'foodapp-27652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDArrCLeoIeLv5hV20sJ2Dw4QcEUfkOhEo',
    appId: '1:792709871499:ios:69dfe12c8f1500da76618e',
    messagingSenderId: '792709871499',
    projectId: 'foodapp-27652',
    storageBucket: 'foodapp-27652.firebasestorage.app',
    iosBundleId: 'com.example.newflutter',
  );
}
